In [1]:
from pathlib import Path
import pdfplumber
import pandas as pd

# Find the project root whether Jupyter starts from the repo root
# or from inside the notebooks folder.
cwd = Path.cwd()

possible_paths = [
    cwd / "source_docs" / "2023-24_sa_fee_memo.pdf",
    cwd.parent / "source_docs" / "2023-24_sa_fee_memo.pdf",
]

pdf_path = next(
    (path.resolve() for path in possible_paths if path.exists()),
    None
)

print("Current working directory:", cwd)
print("PDF found:", pdf_path)

Current working directory: c:\GitHub Projects\seattle-central-sa-budget-dashboard\notebooks
PDF found: C:\GitHub Projects\seattle-central-sa-budget-dashboard\source_docs\2023-24_sa_fee_memo.pdf

In [2]:
with pdfplumber.open(pdf_path) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_number, page in enumerate(pdf.pages, start=1):
        text = page.extract_text()

        print("\n" + "=" * 70)
        print(f"PAGE {page_number}")
        print("=" * 70)

        if text:
            print(text[:1500])
        else:
            print("No readable text detected.")

Number of pages: 12

======================================================================
PAGE 1
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
M E M O R A N D U M
DATE: March 24, 2023
FROM: Jinyang Xia, ASC Executive of Finance
To: Dr. Bradley Lane, Ph.D., Interim President
MR. Kao Lezheo, M.Ed., Interim Vice President of Student Services
Cc: Ricardo Leyva-Puebla, M.A., Dean of Student Development
RE: 2023-2024 S&A Budget Committee Report
The attached copies of the Seattle Central 2023-2024 Services and Activities Fees (S&A) budget
reflect the thoughtful and detailed work on the part of the S&A Budget Committee of the Associated
Student Council (ASC). The committee included myself and students Tamara Happy Yap, Ivan
Fernandez Victoria, Thongtot “Charlie” Ridhirong, Qimuge “Lucy” Xunren, Yimitijiang “Yimi”
Shayiremu, and Nhi “Amy” Nguyen.
These students met weekly during Fall and Winter quarters. During Fall quarter, their work included
S&A Committee orientation, learning the Killian guidelines, Washington Administrative Code, Revised
Code of Washington, Seattle Colleges District Policies, and Procedural Manual, as well as updating
the timeline to make sure to align with the Board of Trustees. Based on last year’s S&A Committee
feedback, we introduced a new web-based application. We faced some glitches but were able to
work them out. We provided two workshops giving out prospective applicants an opportunity to ask
questions and become familiar with the application process. The application was due at th

======================================================================
PAGE 2
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
allocation. Program cuts range from 66% to 1%. In allocating program funding, the committee
considered the individual impact the reduction would have on service to students. It also considered
if there would be other resources or programs that would be able to provide those same services or
additional funding. Other criteria that the committee considered were to reduce the impact on
salaries for all who have worked tirelessly during these troubled times to serve us all. We tried not to
reduce funds for programs that would affect providing sufficient services to support the student body
on their academic success. Other criterial included the following:
• Assessments put in place to measure service satisfaction student feedback and student
success after their use of the service
• Data tracked and benchmarked/scheduled
• Who does the program serve
• Contribution towards anti-racism work
• Budget information that programs/services were on track with projected expenditures
Although this was a challenging task, we are grateful for the opportunity to serve our fellows and
ensure the continuation of the programs that help so many students. All presentations were
compelling and showed thoughtful planning and passion for serving student enrichment and needs.
None of the decisions were easily made, and we fully understand and appreciate the impact of
reduction.
Although w

======================================================================
PAGE 3
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
Seattle Central College S&A Fee Budget 2023-24
(Allocations/Request)
S&A Funded Program 2022-23 Allocations 2023-24 Request 2023-24 Allocation
ASC Book Fund $3,000.00 $3,000.00 $2,000.00
Associated Student Council $56,953.00 $64,539.00 $64,539.00
Bruce Mckenna Writing Center $56,039.01 $0.00 $0
Cultural Programming & Development (CAB) $116,767.00 $116,767.00 $116,767.00
Emergency Fund $25,000.00 $50,000.00 $25,000.00
Equity, Diversity, Inclusion, and Community $11,500.00 $11,500.00 $9,000.00
Info Central $157,950.76 $169,521.00 157,950.00
Leadership & Orientation Training $12,600.00 $8,500.00 $8,500.00
Learning Support Network $419,159.00 $540,680.00 $470,430.25
M. Rosetta Hunter Art Gallary $57,513.12 $62,872.00 $57,513.12
Office Management $71,667.33 $74,824.00 $74,824.00
Parent Support Network $25,000.00 $20,000.00 $20,000.00
Phi Theta Kappa $32,755.00 $35,000.00 $35,000.00
Services & Activities Fees Committee - $5,416.00 $5,416.00
SWAP $52,073.00 $68,720.00 $52,073.00
SORC $122,220.00 $120,002.63 $120,002.63
Student Resource Support $136,607.00 $136,000.00 $136,000.00
Student Leadership Program $131,195.78 $140,985.00 $140,985.00
Student Services $0.00 $5,000.00 $0
Wood Technology Center $12,000.00 - $4,000.00
Total $1,500,000.00 $1,633,326.63 $1,500,000.00

======================================================================
PAGE 4
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
Service & Activities Fee Funded Program Description
S&A Fee Funded Program Brief Description
ASC Book Fund ASC Book Fund makes textbooks and other learning materials available to
students who are unable to purchase them. Textbooks are bought and
placed in the reserve section of the library. Other learning materials are
purchased as the need for them arises.
Associated Student Council The Associated Student Council (ASC) serves as the official student
government and represents Seattle central students on various
committees, college councils and initiatives for students and by students.
They are also responsible for representing student interests to the college
administration and facilitating the organization of a broad range of
student committees that work to address issues and concerns and
promote students' success and enhance the students' experience at
Seattle Central.
Cultural Programming & CAB provides programming on campus through the College
Development (CAB) Activities Board, a team of students who develop and organize events and
activities on campus that celebrate the diversity of our community and
promote student involvement and collaboration among student
organizations.
Emergency Fund Emergency funds offer one-time financial help to students experiencing
an immediate or emergent financial hardship that will hinder their ability
to persist in education

======================================================================
PAGE 5
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
M. Rosetta Hunter Art Gallery The Art Gallery provides a formal venue for the Seattle Central
community to experience the visual arts. The gallery emphasizes the
display of student works and complements these with shows by
professional local and regional artists as well as touring exhibits. These
exhibitions are chosen to align with the mission of the gallery and Seattle
Central as a whole.
Office Management The Front Office of Student Leadership provides centralized services for
all other S&A Budget funded programs and is the primary point of contact
for students, employees, and the community.
Parent Support Network The childcare assistance funding aims to assist with the high cost of
childcare to help relieve the financial burden. Their student support
specialist oversees the funding and makes students aware of availability.
The resource specialist also connects students with city and community to
support childcare.
Phi Theta Kappa PTK provides numerous benefits to its members, including access to
scholarships, leadership development opportunities, and networking
events. PTK helps to foster a sense of community and belonging on
campus and enhances the reputation of Seattle Central College.
Services & Activities Fee This committee is organized, convened, and chaired by the Associated
Committee Student Council Executive Officer of Finance, administratively advi

======================================================================
PAGE 6
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
Services & Activities Fee Budget Request
(For the 2023-24 fiscal year)
BUDGET REQUEST DUE – JANUARY 14, 2022
Criteria for Funding Decisions
It is by means of Student Services and Activities Fees that the campus operates student
programs, services, and activities in accordance with RCW.15.041-.045. These fees may
not be used to fund instructional programs or to replace any activity covered by the
State Board Allocations model.
The student S & A Fee Budget Committee's target is to fund activities, services and
programs that are diverse and extensive, so that priority consideration will be given to
requests based on:
● If they provide concrete examples of what they do.
● Assessments are in place to continually measure service satisfaction, student
feedback, and student success.
● Data is tracked, show’s goal achievement, success of program, services provided
and used etc.
● The program helps students navigate through the system.
● Budget sheets are provided and with a clear description for underspending,
overspending, or budget justification.

======================================================================
PAGE 7
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
APPLICATION CONTENT & QUESTIONS
Services and activities (S&A) fees are used for the sole purpose of funding student activities and programs.
By means of this S&A budgeting process, students review budget proposals and send recommendations
for consideration by the College's Board of Trustees and Executive administration to the extent that such
budget recommendations are intended to be funded by services and activities fees
Budget Request Questions for 2023-2024 Service and Activities Fees Funds
Services and Activities fee information
Use of Funds Expectations and Guidelines
Before you continue…
The S&A Committee members thank you for your service to the school. We know that each one of you is
fully and wholeheartedly committed to promoting student success. Your work speaks for itself. Each
year, the S&A committee looks forward to learning more about the life-changing work you do. We take
pride in the work you do, so we hope you do as well.
For more information on S&A guidelines please see our guideline page
(https://seattlecentral.edu/services-and-activities-fees-guidelines):
Deadline: SUBMIT electronically through the website by January 6 2023
Application Information requested
Name, email, and what is the name of the service, department, or program requesting funds.
Narrative Questions requested
WHAT do you do? [Describe how funding being requested in this appl

======================================================================
PAGE 8
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
funding. You are not required to request funding in each category. You may choose one category for
your application and submit that as your application. However, you will be asked to provide a list of
purchases intended for this request, or justification for use of funding in the category used for this
application.
Files for Submission and Signatures requested
Please upload a letter of impact statement:
Prompt: How has this program helped you complete your degree? How did this help your personal
development?
Impact Statement File
Please upload any files you believe support your application
Please upload assessments, data, or other documents.

======================================================================
PAGE 9
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
RESOURCE PROVIDED
SERVICES AND ACTIVITIES FEE
COMMITTEE ANNUAL FUNDING
REQUEST PROCESS TIMELINE
2021-22
November 1, 2021 S&A Budget Requests Forms Available
November 15, 11:00 AM Budget Request Application Workshop
November 16, 1:00 PM Budget Request Application Workshop
January 14, 2022 Budget Request Due
January 21 – February 11 Budget Hearings
Finalized proposed budget allocations distributed and notify
February 18
applicants of awards
Budget appeals hearings: Applicants have an opportunity to
February 25
meet with committee to request changes to their award
Open hearings for proposed budget: Share proposed final budget
March 4
with the college community
S&A presents budget recommendation to ASC for review and
March 7
ratification
S&A presents ratified 2022-23 budget to President and Cabinet
April 12
May 12 S&A Presentation to the Board of Trustee Board of
Trustees reviews proposed budget
June 9 Board of Trustees acts on proposed budget.

======================================================================
PAGE 10
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
RESOURCE PROVIDED
Criteria for Funding Decisions Explanation
It is by means of Student Services and Activities Fees that the campus operates student programs,
services, and activities in accordance with RCW.15.041-.045. These fees may not be used to fund
instructional programs or to replace any activity covered by the State Board Allocations model.
The student S & A Fee Budget Committee's goal is to fund activities, services and programs that are
varied and far reaching, so that priority consideration will be given to requests based on:
● The degree to which the program or activity is Accessible, Collaborative, Diverse, Inclusive, Equitable,
Student Engaging, and Innovative
Does the program bring a unique service to the campus? Does it support groups of students that might
not otherwise be serviced? Does the program engage students to the campus community?
● The potential impact of the program or activity on student success
How does the program help students be successful in achieving their academic goals?
● The number of students served
Does the program track students' use of programs or activities?
● The benefit to students
Does the program highlight how it benefits the students?
● Supporting Data and Assessment tools
Does the program have data that shows program success (qualitative and quantitative)? Does the
program collect student satisfaction surveys, fo

======================================================================
PAGE 11
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
RESOURCE PROVIDED
S & A Budget Committee Funding Request Score Sheet
1. Mission, Objectives, Goals, Outcomes (2 points possible)
Are the following explained? Mission, Purpose, Objective, Goals, and Outcomes... how in depth
No reference
Mentions Operational Plan, briefly explains mission, purpose, objective, goals and
outcomes
Demonstrates, with concreate examples, how this budget follows the Operational plan
using the mission, purpose, objective, goals, and outcomes
2. How do the services provided in this proposal promote student success? (2 points possible)
Think about how students benefit directly and indirectly, the role of employees and their factor in the
program, relevant experience in the position as facilitator.
Request shows student involvement
Request demonstrates how students benefit, mentions staff involvement
Request shows how students benefit directly and indirectly, talks about the employees
and their role in the program as well as provides examples.
3. How well is Data tracked and benchmarked/scheduled...
Data is key, but doesn’t necessarily mean numbers in terms of quantity, quality over quantity. Goal
achievement, program success, services provided and used, numbers of students served (quantity
doesn't matter, just want to see this is being tracked) (2 points possible)
Data is provided, not relevant to request, no real measurements kept, no me

======================================================================
PAGE 12
======================================================================
ASSOCIATED STUDENT COUNCIL
1701 Broadway, Seattle, WA 98122
Main 206.934.4057
asc-finance.central@seattlecentral.edu
6. Budget Adjustment (2 points possible)
Provided a list of areas of decrease/reduction
Provided an explanation on how a reduction will impact services

In [3]:
with pdfplumber.open(pdf_path) as pdf:
    for page_number, page in enumerate(pdf.pages, start=1):
        tables = page.extract_tables()

        print(
            f"Page {page_number}: "
            f"{len(tables)} table(s) detected"
        )

        for table_number, table in enumerate(tables, start=1):
            print(f"\nTable {table_number}")
            for row in table[:10]:
                print(row)

Page 1: 0 table(s) detected
Page 2: 0 table(s) detected
Page 3: 1 table(s) detected

Table 1
['S&A Funded Program 2022-23 Allocations 2023-24 Request', None, None, '2023-24 Allocation']
['ASC Book Fund', '$3,000.00', '$3,000.00', '$2,000.00']
['Associated Student Council', '$56,953.00', '$64,539.00', '$64,539.00']
['Bruce Mckenna Writing Center', '$56,039.01', '$0.00', '$0']
['Cultural Programming & Development (CAB)', '$116,767.00', '$116,767.00', '$116,767.00']
['Emergency Fund', '$25,000.00', '$50,000.00', '$25,000.00']
['Equity, Diversity, Inclusion, and Community', '$11,500.00', '$11,500.00', '$9,000.00']
['Info Central', '$157,950.76', '$169,521.00', '157,950.00']
['Leadership & Orientation Training', '$12,600.00', '$8,500.00', '$8,500.00']
['Learning Support Network', '$419,159.00', '$540,680.00', '$470,430.25']
Page 4: 8 table(s) detected

Table 1
['S&A Fee Funded Program', 'Brief Description']
['ASC Book Fund', 'ASC Book Fund makes textbooks and other learning materials available to\nstudents who are unable to purchase them. Textbooks are bought and\nplaced in the reserve section of the library. Other learning materials are\npurchased as the need for them arises.']
['Associated Student Council', "The Associated Student Council (ASC) serves as the official student\ngovernment and represents Seattle central students on various\ncommittees, college councils and initiatives for students and by students.\nThey are also responsible for representing student interests to the college\nadministration and facilitating the organization of a broad range of\nstudent committees that work to address issues and concerns and\npromote students' success and enhance the students' experience at\nSeattle Central."]
['Cultural Programming &\nDevelopment (CAB)', 'CAB provides programming on campus through the College\nActivities Board, a team of students who develop and organize events and\nactivities on campus that celebrate the diversity of our community and\npromote student involvement and collaboration among student\norganizations.']
['Emergency Fund', 'Emergency funds offer one-time financial help to students experiencing\nan immediate or emergent financial hardship that will hinder their ability\nto persist in education at Seattle Central.']
['Equity, Diversity, Inclusion, and\nCommunity', 'The Office of Equity, Diversity, and Inclusion promotes institutional\nresponsiveness to the needs of students of color and students of diverse\ncultural backgrounds. They provide leadership opportunities for the\ndevelopment and implementation services, programs, projects, and\ncurricula that promote diversity, equity, and social justice.']
['Information Central', 'Information Central is a student-led space dedicated to creating\nconnections, navigating systems and promoting engagement\nopportunities in the service of student success and agency.']
['Leadership & Orientation\nTraining', 'Leadership & Orientation Training secures funds for our pre-fall training\nand orientation, quarterly Student Leadership institutes, and ongoing\nprofessional development for student employees and the student body of\nSeattle Central College, creating a robust College-wide Student Leadership\nProgram.']
['Learning Support Network', 'Learning Support Network provides accessible and quality academic\nsupport to Seattle Central students by improving comprehension,\nincreasing competence, instilling confidence and promoting success. Their\nnetwork includes the BE Learning Center, the SAM Learning Center, the\nBruce McKenna Writing Center, IT & BTM Program Tutoring, and satellite\ntutor locations.']

Table 2
['The Associated Student Council (ASC) serves as the official student']
['government and represents Seattle central students on various']
['committees, college councils and initiatives for students and by students.']
['They are also responsible for representing student interests to the college']
['administration and facilitating the organization of a broad range of']
['student committees that work to address issues and concerns and']
["promote students' success and enhance the students' experience a"]
['Seattle Central.']

Table 3
['Activities Board, a team of students who develop and organize events and']
['activities on campus that celebrate the diversity of our community and']
['promote student involvement and collaboration among student']
['organizations.']

Table 4
['Emergency funds offer one-time financial help to students experiencing']
['an immediate or emergent financial hardship that will hinder their ability']
['to persist in education at Seattle Central.']

Table 5
['The Office of Equity, Diversity, and Inclusion promotes institutional']
['responsiveness to the needs of students of color and students of diverse']
['cultural backgrounds. They provide leadership opportunities for the']
['development and implementation services, programs, projects, and']
['curricula that promote diversity, equity, and social justice.']

Table 6
['Information Central is a student-led space dedicated to creating']
['connections, navigating systems and promoting engagement']
['opportunities in the service of student success and agency.']

Table 7
['and orientation, quarterly Student Leadership institutes, and ongoing']
['professional development for student employees and the student body of']
['Seattle Central College, creating a robust College-wide Student Leadership']
['Program.']

Table 8
['support to Seattle Central students by improving comprehension,']
['increasing competence, instilling confidence and promoting success. Their']
['network includes the BE Learning Center, the SAM Learning Center, the']
['Bruce McKenna Writing Center, IT & BTM Program Tutoring, and satellite']
['tutor locations.']
Page 5: 12 table(s) detected

Table 1
['M. Rosetta Hunter Art Gallery', 'The Art Gallery provides a formal venue for the Seattle Central\ncommunity to experience the visual arts. The gallery emphasizes the\ndisplay of student works and complements these with shows by\nprofessional local and regional artists as well as touring exhibits. These\nexhibitions are chosen to align with the mission of the gallery and Seattle\nCentral as a whole.']
['Office Management', 'The Front Office of Student Leadership provides centralized services for\nall other S&A Budget funded programs and is the primary point of contact\nfor students, employees, and the community.']
['Parent Support Network', 'The childcare assistance funding aims to assist with the high cost of\nchildcare to help relieve the financial burden. Their student support\nspecialist oversees the funding and makes students aware of availability.\nThe resource specialist also connects students with city and community to\nsupport childcare.']
['Phi Theta Kappa', 'PTK provides numerous benefits to its members, including access to\nscholarships, leadership development opportunities, and networking\nevents. PTK helps to foster a sense of community and belonging on\ncampus and enhances the reputation of Seattle Central College.']
['Services & Activities Fee\nCommittee', 'This committee is organized, convened, and chaired by the Associated\nStudent Council Executive Officer of Finance, administratively advised by\nthe Dean of Student Development or the appointed designee, and\nassisted by the Administrative Assistant who monitors the budgets.']
['Student Web and Publication\n(SWAP)', "SWAP reports the news that's relevant for the Seattle Central community,\nthe first and foremost members being students; and secondly, to provide\nstudents with a platform that amplifies their voices."]
['Student Organization Resource\nCenter (SORC)', 'SORC helps Student Organizations with funding access, resources,\nleadership practice, and training. We are committed to providing spaces\nfor students who want to find a sense of belonging as well as empower\nthem to lead their communities.']
['Student Resource Support', 'Student resource specialists are guided by the mission of student support\nas an equity and justice-oriented space that recognizes that academic\nsuccess is tied to addressing students’ wholistic needs. The resource\nspecialists provide a basic needs center approach to college completion.']
['Student Leadership Program', 'Student Leadership facilitates leadership development and supports\nstudent involvement, creating connections for student success.']
['Wood Technology Center', 'The Wood Technology Center operates on a satellite campus, which\nmakes the role of the student council an important link between the Main\nCampus and their student body. They strive to be a resource of\ninformation for the students of the Wood Technology Center.']

Table 2
['community to experience the visual arts. The gallery emphasizes the']
['display of student works and complements these with shows b']

Table 3
['exhibitions are chosen to align with the mission of the gallery and Seattl']
['Central as a whole.']

Table 4
['The Front Office of Student Leadership provides centralized services for']
['all other S&A Budget funded programs and is the primary point of contact']
['for students, employees, and the community.']

Table 5
['The childcare assistance funding aims to assist with the high cost of']
['childcare to help relieve the financial burden. Their student support']
['specialist oversees the funding and makes students aware of availability']
['The resource specialist also connects students with city and community to']
['support childcare.']

Table 6
['PTK provides numerous benefits to its members, including access to']
['scholarships, leadership development opportunities, and networkin']

Table 7
['This committee is organized, convened, and chaired by the Associated']
['Student Council Executive Officer of Finance, administratively advised b']
['the Dean of Student Development or the appointed designee, and']

Table 8
['the first and foremost members being students; and secondly, to provid']
['students with a platform that amplifies their voices.']

Table 9
['leadership practice, and training. We are committed to providing spaces']
['for students who want to find a sense of belonging as well as empower']
['them to lead their communities.']

Table 10
['success is tied to addressing students’ wholistic needs. The resource']
['specialists provide a basic needs center approach to college completion']

Table 11
['Student Leadership facilitates leadership development and support']
['student involvement, creating connections for student success.']

Table 12
['The Wood Technology Center operates on a satellite campus, which']
['makes the role of the student council an important link between the Main']
['Campus and their student body. They strive to be a resource of']
['information for the students of the Wood Technology Center.']
Page 6: 0 table(s) detected
Page 7: 1 table(s) detected

Table 1
['Narrative Questions requested']
['WHAT do you do? [Describe how funding being requested in this application will be or was used.)']
['HOW do you know it’s working? (What assessments (or audit) are you using or plan to use? What goals']
['have you met? How do you, or will you, know you met them?)']
['WHAT data do you have to demonstrate your program is working? What data will you collect? (Please']
['upload any relevant documents on the next page.)']
['WHO do you serve? (Type of Students served)']
['HOW MANY students do you serve? (# Of Students served)']
["Please describe how this request for funding will impact or support the college's commitment to anti-"]
['racism work?']
Page 8: 1 table(s) detected

Table 1
['funding. You are not required to request funding in each category. You may choose one category for']
['your application and submit that as your application. However, you will be asked to provide a list of']
['purchases intended for this request, or justification for use of funding in the category used for this']
['application.']
['Files for Submission and Signatures requested']
['Please upload a letter of impact statement:']
['Prompt: How has this program helped you complete your degree? How did this help your personal']
['development?']
['Impact Statement File']
['Please upload any files you believe support your application']
Page 9: 6 table(s) detected

Table 1
['November 15, 11:00 AM', 'Budget Request Application Workshop']
['', '']

Table 2
['January 14, 2022', 'Budget Request Due']
['', '']

Table 3
['February 18', 'Finalized proposed budget allocations distributed and notify']
[None, 'applicants of awards']
['', None]
[None, '']

Table 4
['March 4', 'Open hearings for proposed budget: Share proposed final budget']
[None, 'with the college community']
['', None]
[None, '']

Table 5
['April 12', 'S&A presents ratified 2022-23 budget to President and Cabinet']
[None, '']
['', None]

Table 6
['June 9', 'Board of Trustees acts on proposed budget.']
['', '']
Page 10: 0 table(s) detected
Page 11: 0 table(s) detected
Page 12: 0 table(s) detected

In [4]:
with pdfplumber.open(pdf_path) as pdf:
    page = pdf.pages[2]  # Page 3
    table = page.extract_tables()[0]

# Skip the first row because it is the merged PDF header.
budget_rows = table[1:]

df_2023_24_raw = pd.DataFrame(
    budget_rows,
    columns=[
        "program_name_raw",
        "allocation_2022_23_raw",
        "request_2023_24_raw",
        "allocation_2023_24_raw",
    ],
)

display(df_2023_24_raw)

print("\nRows extracted:", len(df_2023_24_raw))

,program_name_raw,allocation_2022_23_raw,request_2023_24_raw,allocation_2023_24_raw
0,ASC Book Fund,"$3,000.00","$3,000.00","$2,000.00"
1,Associated Student Council,"$56,953.00","$64,539.00","$64,539.00"
2,Bruce Mckenna Writing Center,"$56,039.01",$0.00,$0
3,Cultural Programming & Development (CAB),"$116,767.00","$116,767.00","$116,767.00"
4,Emergency Fund,"$25,000.00","$50,000.00","$25,000.00"
5,"Equity, Diversity, Inclusion, and Community","$11,500.00","$11,500.00","$9,000.00"
6,Info Central,"$157,950.76","$169,521.00","157,950.00"
7,Leadership & Orientation Training,"$12,600.00","$8,500.00","$8,500.00"
8,Learning Support Network,"$419,159.00","$540,680.00","$470,430.25"
9,M. Rosetta Hunter Art Gallary,"$57,513.12","$62,872.00","$57,513.12"
10,Office Management,"$71,667.33","$74,824.00","$74,824.00"
11,Parent Support Network,"$25,000.00","$20,000.00","$20,000.00"
12,Phi Theta Kappa,"$32,755.00","$35,000.00","$35,000.00"
13,Services & Activities Fees Committee,-,"$5,416.00","$5,416.00"
14,SWAP,"$52,073.00","$68,720.00","$52,073.00"
15,SORC,"$122,220.00","$120,002.63","$120,002.63"
16,Student Resource Support,"$136,607.00","$136,000.00","$136,000.00"
17,Student Leadership Program,"$131,195.78","$140,985.00","$140,985.00"
18,Student Services,$0.00,"$5,000.00",$0
19,Wood Technology Center,"$12,000.00",-,"$4,000.00"

Rows extracted: 20

In [5]:
print("First 5 rows:")
display(df_2023_24_raw.head())

print("Last 5 rows:")
display(df_2023_24_raw.tail())

First 5 rows:

,program_name_raw,allocation_2022_23_raw,request_2023_24_raw,allocation_2023_24_raw
0,ASC Book Fund,"$3,000.00","$3,000.00","$2,000.00"
1,Associated Student Council,"$56,953.00","$64,539.00","$64,539.00"
2,Bruce Mckenna Writing Center,"$56,039.01",$0.00,$0
3,Cultural Programming & Development (CAB),"$116,767.00","$116,767.00","$116,767.00"
4,Emergency Fund,"$25,000.00","$50,000.00","$25,000.00"

Last 5 rows:

,program_name_raw,allocation_2022_23_raw,request_2023_24_raw,allocation_2023_24_raw
15,SORC,"$122,220.00","$120,002.63","$120,002.63"
16,Student Resource Support,"$136,607.00","$136,000.00","$136,000.00"
17,Student Leadership Program,"$131,195.78","$140,985.00","$140,985.00"
18,Student Services,$0.00,"$5,000.00",$0
19,Wood Technology Center,"$12,000.00",-,"$4,000.00"

In [6]:
def parse_currency_for_check(value):
    if value is None:
        return 0.0

    value = str(value).strip()

    if value in {"", "-", "—"}:
        return 0.0

    value = (
        value
        .replace("$", "")
        .replace(",", "")
    )

    return float(value)


validation_totals = {
    "2022-23 Allocation": df_2023_24_raw[
        "allocation_2022_23_raw"
    ].apply(parse_currency_for_check).sum(),

    "2023-24 Request": df_2023_24_raw[
        "request_2023_24_raw"
    ].apply(parse_currency_for_check).sum(),

    "2023-24 Allocation": df_2023_24_raw[
        "allocation_2023_24_raw"
    ].apply(parse_currency_for_check).sum(),
}

for label, total in validation_totals.items():
    print(f"{label}: ${total:,.2f}")

2022-23 Allocation: $1,500,000.00
2023-24 Request: $1,633,326.63
2023-24 Allocation: $1,500,000.00

In [7]:
# Create a traceable raw copy
df_2023_24_export = df_2023_24_raw.copy()

df_2023_24_export.insert(
    0,
    "source_document",
    "2023-24_sa_fee_memo.pdf"
)

df_2023_24_export.insert(
    1,
    "source_page",
    3
)

df_2023_24_export.insert(
    2,
    "source_url",
    "https://studentleadership.seattlecentral.edu/sites/"
    "studentleadership.seattlecentral.edu/files/"
    "2023-09/2223-SA-Fees-Memo.pdf"
)

display(df_2023_24_export.head())

,source_document,source_page,source_url,program_name_raw,allocation_2022_23_raw,request_2023_24_raw,allocation_2023_24_raw
0,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,ASC Book Fund,"$3,000.00","$3,000.00","$2,000.00"
1,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Associated Student Council,"$56,953.00","$64,539.00","$64,539.00"
2,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Bruce Mckenna Writing Center,"$56,039.01",$0.00,$0
3,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Cultural Programming & Development (CAB),"$116,767.00","$116,767.00","$116,767.00"
4,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Emergency Fund,"$25,000.00","$50,000.00","$25,000.00"

In [8]:
# Locate the project's data/raw folder
raw_dir_candidates = [
    cwd / "data" / "raw",
    cwd.parent / "data" / "raw",
]

raw_dir = next(
    (path.resolve() for path in raw_dir_candidates if path.exists()),
    None
)

output_path = raw_dir / "2023_24_sa_budget_raw.csv"

df_2023_24_export.to_csv(
    output_path,
    index=False
)

print("Saved to:")
print(output_path)

Saved to:
C:\GitHub Projects\seattle-central-sa-budget-dashboard\data\raw\2023_24_sa_budget_raw.csv

In [9]:
check = pd.read_csv(
    output_path,
    dtype=str,
    keep_default_na=False
)

print("Rows:", len(check))
print("Columns:", len(check.columns))

display(check.head(3))
display(check.tail(3))

Rows: 20
Columns: 7

,source_document,source_page,source_url,program_name_raw,allocation_2022_23_raw,request_2023_24_raw,allocation_2023_24_raw
0,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,ASC Book Fund,"$3,000.00","$3,000.00","$2,000.00"
1,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Associated Student Council,"$56,953.00","$64,539.00","$64,539.00"
2,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Bruce Mckenna Writing Center,"$56,039.01",$0.00,$0

,source_document,source_page,source_url,program_name_raw,allocation_2022_23_raw,request_2023_24_raw,allocation_2023_24_raw
17,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Student Leadership Program,"$131,195.78","$140,985.00","$140,985.00"
18,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Student Services,$0.00,"$5,000.00",$0
19,2023-24_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Wood Technology Center,"$12,000.00",-,"$4,000.00"

In [10]:
pdf_2024_25 = next(
    (
        path.resolve()
        for path in [
            cwd / "source_docs" / "2024-25_sa_fee_memo.pdf",
            cwd.parent / "source_docs" / "2024-25_sa_fee_memo.pdf",
        ]
        if path.exists()
    ),
    None
)

print("PDF found:", pdf_2024_25)

PDF found: C:\GitHub Projects\seattle-central-sa-budget-dashboard\source_docs\2024-25_sa_fee_memo.pdf

In [11]:
with pdfplumber.open(pdf_2024_25) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_number, page in enumerate(pdf.pages, start=1):
        tables = page.extract_tables()

        print(
            f"Page {page_number}: "
            f"{len(tables)} table(s) detected"
        )

        for table_number, table in enumerate(tables, start=1):
            print(f"\nTable {table_number}")

            for row in table[:8]:
                print(row)

Number of pages: 7
Page 1: 0 table(s) detected
Page 2: 0 table(s) detected
Page 3: 1 table(s) detected

Table 1
['S&A Funded Program', '2023-24', '2024-25', '2024-25']
['', 'Allocation', 'Request', 'Allocation']
['ASC Book Fund', '$2,000.00', '$0.00', '$2,000.00']
['Associated Student Council', '$64,539.00', '$93,159.58', '$93,159.58']
['Cultural Programming & Development (CAB)', '$116,767.00', '$122,613.11', '$128,841.99']
['Emergency Fund', '$25,000.00', '$0.00', '$25,000.00']
['Equity, Diversity, Inclusion, and Community', '$9,000.00', '$0.00', '$9,076.80']
['Info Central', '$157,950.00', '$191,489.40', '$195,205.32']
Page 4: 4 table(s) detected

Table 1
['S&A Fee Funded Program', 'Brief Description', None, None, None, None, None, None]
['ASC Book Fund', 'ASC Book Fund makes textbooks and other learning materials\navailable to students who are unable to purchase them. Textbooks\nare bought and placed in the reserve section of the library. Other\nlearning materials are purchased as the need for them arises.', None, None, None, None, None, None]
['Associated Student Council', "The Associated Student Council (ASC) serves as the official\nstudent government and represents Seattle central students on\nvarious committees, college councils and initiatives for students and\nby students. They are also responsible for representing student\ninterests to the college administration and facilitating the\norganization of a broad range of student committees that work to\naddress issues and concerns and promote students' success and\nenhance the students' experience at Seattle Central.", None, None, None, None, None, None]
['Cultural Programming &\nDevelopment (CAB)', 'CAB provides programming on campus through the College\nActivities Board, a team of students who develop and organize\nevents and activities on campus that celebrate the diversity of our\ncommunity and promote student involvement and collaboration\namong student organizations.', None, None, None, None, None, None]
['Emergency Fund', 'Emergency funds offer one-time financial help to students\nexperiencing an immediate or emergent financial hardship that will\nhinder their ability to persist in education at Seattle Central.', None, None, None, None, None, None]
['Equity, Diversity, Inclusion, and\nCommunity', '', 'The Office of Equity, Diversity, and Inclusion promotes institutiona', None, None, None, None, None]
[None, None, 'responsiveness to the needs of students of color and students of', None, None, None, None, None]
[None, None, 'diverse', 'cultural backgrounds. They provide leadership opportunities', None, None, None, None]

Table 2
['The Associated Student Council (ASC) serves as the official', None, None, None, None, None, None, None, None, None]
['student', 'government and represents Seattle central students on', None, None, None, None, None, None, None, None]
['various', 'committees, college councils and initiatives for students and', None, None, None, None, None, None, None, None]
['by students', None, '.', 'They are also responsible for representing student', None, None, None, None, None, None]
['interests to the college', None, None, None, '', 'administration and facilitating the', None, None, None, None]
['organization of a broad range of', None, None, None, None, None, '', 'student committees that work to', None, None]
['address issues and concerns and', None, None, None, None, None, None, None, '', "promote students' success and"]
["enhance the students' experience at", None, None, None, None, None, None, None, None, None]

Table 3
['Activities Board, a team of students who develop and organize', None, None]
['events and', 'activities on campus that celebrate the diversity of our', None]
['community and', None, 'promote student involvement and collaboration']
['among student', None, 'organizations.']

Table 4
['Emergency funds offer one-time financial help to students', None]
['experiencing', 'an immediate or emergent financial hardship that will']
['hinder their ability', None]
Page 5: 1 table(s) detected

Table 1
['M. Rosetta Hunter Art Gallery', 'The Art Gallery provides a formal venue for the Seattle Central\ncommunity to experience the visual arts. The gallery emphasizes\nthe display of student works and complements these with shows by\nprofessional local and regional artists, as well as touring exhibits.\nThese exhibitions are chosen to align with the mission of the gallery\nand Seattle Central as a whole.', None, None, None, None, None]
['Office Management', 'The Front Office of Student Leadership provides centralized\nservices for all other S&A Budget funded programs and is the\nprimary point of contact for students, employees, and the\ncommunity.', None, None, None, None, None]
['Parent Support Network', 'The childcare assistance funding aims to assist with the high cost of\nchildcare to help relieve the financial burden. Their student support\nspecialist oversees the funding and makes students aware of\navailability. The resource specialist also connects students with the\ncity and community to support childcare.', None, None, None, None, None]
['Phi Theta Kappa', 'PTK provides numerous benefits to its members, including access\nto scholarships, leadership development opportunities, and\nnetworking events. PTK helps to foster a sense of community and\nbelonging on campus and enhances the reputation of Seattle\nCentral College.', None, None, None, None, None]
['Services & Activities Fee\nCommittee', 'This committee is organized, convened, and chaired by the\nAssociated Student Council Executive Officer of Finance,\nadministratively advised by the Dean of Student Development or\nthe appointed designee, and assisted by the Administrative\nAssistant who monitors the budgets.', None, None, None, None, None]
['Student Web and Publication\n(SWAP)', "SWAP reports the news that's relevant for the Seattle Central\ncommunity, the first and foremost members being students; and\nsecondly, to provide students with a platform that amplifies their\nvoices.", None, None, None, None, None]
['Student Organization\nResource Center (SORC)', 'SORC helps Student Organizations with funding access, resources,\nleadership practice, and training. We are committed to providing\nspaces for students who want to find a sense of belonging as well\nas empower them to lead their communities.', None, None, None, None, None]
['Student Resource Support', 'Student resource specialists are guided by the mission of student\nsupport as an equity and justice-oriented space that recognizes that\nacademic success is tied to addressing students’ wholistic needs.\nThe resource specialists provide a basic needs center approach to\ncollege completion.', None, None, None, None, None]
Page 6: 1 table(s) detected

Table 1
['', None, None, '', None, None]
['', 'Meeting Date(s)', '', '', 'Description and Action', '']
['', None, None, '', None, None]
['October – December 2023', None, None, 'S&A Fee Committee recruitment & training', None, None]
['November 13, 2023', None, None, 'S&A Budget Requests Forms available\nNotify campus of budget request availability', None, None]
['December 8-9, 2023', None, None, 'Training for committee members', None, None]
['January 14, 2024', None, None, 'Budget Request due', None, None]
['January 21-24, 2024', None, None, 'Budget hearings', None, None]
Page 7: 1 table(s) detected

Table 1
['', '0-1', '2-3', '4-5']
['Department/Program\noutlines their purpose, goals\nand outcomes.\nData and/or student\nfeedback are used to\nmeasure outcomes of\nsuccess and/or\nsatisfaction.', 'Purpose, goals and/or\noutcomes not clear.\nLittle or no measurements\nor metrics in place to assess\nstudent success and/or\nsatisfaction.\nIf data is provided, it is not\nrelevant to the adjustment\nrequest.', 'Purpose, goals and\noutcomes clear.\nData provided demonstrates\ngoal achievement and\nprogram success through\nservices provided.\nData and/or student\nfeedback regarding success\nor satisfaction measured one\ntime; no continuous\ntracking.', 'Purpose, goals and outcomes\nvery clear.\nOutcomes measured and\nachieved as shown by data\nand/or student feedback.\nAssessments in place to\ncontinually measure service\nsatisfaction, student feedback\nand student success.']
['Students are involved in the\ndevelopment and\nimplementation of the\nprogram or activity.', 'Students have little or no\ninvolvement in program\nsuccess.\nStudents have little\ninvolvement in planning\nand/or implementation of\nprogram(s), event(s) and/or\nservice(s).', 'Students contribute to\nplanning process and\nimplementation of\nprogram(s), event(s) and/or\nservice(s).', 'Students are centered in\nplanning and delivery of\nprogram and/or service.\nStudents play a leadership\nrole in planning and\nimplementation of program(s),\nevent(s) and/or service(s).']
['Department/Program\ndemonstrates clear need of\nbudget increase to serve\nstudents.', 'Not clear how funds have\nbeen used and will be\nused.', 'Department/Program\noutlines how funding has\nbeen used and will be used.\nShares some examples of\nhow funding has been used\nand will be used.', 'In application and/or hearing,\nbudget manager clearly\narticulates how increased\nfunding will ensure student\nsuccess and support.\nIncludes detailed calculations\nand projections of need and\nbenefit to students.']
['Department/Program\ndemonstrates commitment\nto antiracism and historically\nunderserved and\nmarginalized student\npolulation', 'No response or vague\nmention of antiracism work.\nDoes not discuss how\ndepartment/program\nsupports students from\nhistorically underserved and\nmarginalized communities.', 'Provides some examples of\nhow department/program\nsupports students from\nhistorically underserved and\nmarginalized communities.', 'Provides specific examples of\nhow department/program\nsupports students from\nhistorically underserved and\nmarginalized communities.\nWorks in collaboration with\nother departments and\nprograms to provide more\nholistic student support\nacross identities.']
['Department/program\nprovides programming and\nsupport across a wide\nnumber and students across\na variety of identities and\nbackgrounds.', 'Only serves a particular\ngroup of students and/or\nless than 50 students during\nthe year.', 'Serves students across a\nfew groups with an\nintersection of identities.\nProvides few examples of\nservices and support for\nmultiple groups of students.', 'Serves students across\nmultiple groups with an\nintersection of identities.\nProvides multiple specific\nexamples of services and\nsupport for multiple groups of\nstudents.']
['TOTAL SCORE: ____ / 25\npts', '', '', '']

In [12]:
with pdfplumber.open(pdf_2024_25) as pdf:
    page = pdf.pages[2]  # Page 3
    table = page.extract_tables()[0]

# First two rows are the multi-row table header
budget_rows_2024_25 = table[2:]

df_2024_25_raw = pd.DataFrame(
    budget_rows_2024_25,
    columns=[
        "program_name_raw",
        "allocation_2023_24_raw",
        "request_2024_25_raw",
        "allocation_2024_25_raw",
    ],
)

display(df_2024_25_raw)

print("\nRows extracted:", len(df_2024_25_raw))

,program_name_raw,allocation_2023_24_raw,request_2024_25_raw,allocation_2024_25_raw
0,ASC Book Fund,"$2,000.00",$0.00,"$2,000.00"
1,Associated Student Council,"$64,539.00","$93,159.58","$93,159.58"
2,Cultural Programming & Development (CAB),"$116,767.00","$122,613.11","$128,841.99"
3,Emergency Fund,"$25,000.00",$0.00,"$25,000.00"
4,"Equity, Diversity, Inclusion, and Community","$9,000.00",$0.00,"$9,076.80"
5,Info Central,"$157,950.00","$191,489.40","$195,205.32"
6,Leadership & Orientation Training,"$16,384.00",$0.00,"$16,384.00"
7,Learning Support Network,"$470,430.25","$473,391.87","$473,391.87"
8,M. Rosetta Hunter Art Gallery,"$57,513.00","$65,282.72","$58,513.79"
9,Office Management,"$74,824.00","$132,111.01","$85,967.23"
10,Child Assist Program,"$20,000.00",$0.00,"$20,000.00"
11,Phi Theta Kappa,"$35,000.00",$0.00,"$36,047.71"
12,Services & Activities Fees Committee,"$7,500.00","$24,131.32","$24,131.32"
13,Seattle Collegian,"$52,073.00","$79,142.00","$79,142.00"
14,Student Organization Hub,"$120,002.63","$123,000.00","$127,811.35"
15,Student Resource Support,"$139,203.30",$0.00,"$139,203.30"
16,Student Leadership Program,"$140,985.00","$169,417.55","$169,417.55"
17,Student Engagement,$0.00,$0.00,"$45,714.70"
18,Wood Technology Center,"$4,000.00","$28,860.00","$4,000.00"
19,Total,"$1,513,171.18","$1,502,598.56","$1,733,008.51"
20,,,,

Rows extracted: 21

In [13]:
print("First 5 rows:")
display(df_2024_25_raw.head())

print("Last 5 rows:")
display(df_2024_25_raw.tail())

First 5 rows:

,program_name_raw,allocation_2023_24_raw,request_2024_25_raw,allocation_2024_25_raw
0,ASC Book Fund,"$2,000.00",$0.00,"$2,000.00"
1,Associated Student Council,"$64,539.00","$93,159.58","$93,159.58"
2,Cultural Programming & Development (CAB),"$116,767.00","$122,613.11","$128,841.99"
3,Emergency Fund,"$25,000.00",$0.00,"$25,000.00"
4,"Equity, Diversity, Inclusion, and Community","$9,000.00",$0.00,"$9,076.80"

Last 5 rows:

,program_name_raw,allocation_2023_24_raw,request_2024_25_raw,allocation_2024_25_raw
16,Student Leadership Program,"$140,985.00","$169,417.55","$169,417.55"
17,Student Engagement,$0.00,$0.00,"$45,714.70"
18,Wood Technology Center,"$4,000.00","$28,860.00","$4,000.00"
19,Total,"$1,513,171.18","$1,502,598.56","$1,733,008.51"
20,,,,

In [14]:
# Remove the completely blank extraction row
df_2024_25_raw = df_2024_25_raw[
    df_2024_25_raw["program_name_raw"].notna()
].copy()

df_2024_25_raw["program_name_raw"] = (
    df_2024_25_raw["program_name_raw"].astype(str).str.strip()
)

df_2024_25_raw = df_2024_25_raw[
    df_2024_25_raw["program_name_raw"] != ""
].copy()

# Preserve the reported Total row separately
reported_total_2024_25 = df_2024_25_raw[
    df_2024_25_raw["program_name_raw"].str.lower() == "total"
].copy()

# Program-level rows only
df_2024_25_programs = df_2024_25_raw[
    df_2024_25_raw["program_name_raw"].str.lower() != "total"
].copy()

print("Program rows:", len(df_2024_25_programs))

display(reported_total_2024_25)

Program rows: 19

,program_name_raw,allocation_2023_24_raw,request_2024_25_raw,allocation_2024_25_raw
19,Total,"$1,513,171.18","$1,502,598.56","$1,733,008.51"

In [15]:
calculated_totals_2024_25 = {
    "2023-24 Allocation": df_2024_25_programs[
        "allocation_2023_24_raw"
    ].apply(parse_currency_for_check).sum(),

    "2024-25 Request": df_2024_25_programs[
        "request_2024_25_raw"
    ].apply(parse_currency_for_check).sum(),

    "2024-25 Allocation": df_2024_25_programs[
        "allocation_2024_25_raw"
    ].apply(parse_currency_for_check).sum(),
}

reported_totals_2024_25 = {
    "2023-24 Allocation": parse_currency_for_check(
        reported_total_2024_25.iloc[0]["allocation_2023_24_raw"]
    ),

    "2024-25 Request": parse_currency_for_check(
        reported_total_2024_25.iloc[0]["request_2024_25_raw"]
    ),

    "2024-25 Allocation": parse_currency_for_check(
        reported_total_2024_25.iloc[0]["allocation_2024_25_raw"]
    ),
}

for label in calculated_totals_2024_25:
    calculated = calculated_totals_2024_25[label]
    reported = reported_totals_2024_25[label]

    print(f"{label}")
    print(f"  Calculated: ${calculated:,.2f}")
    print(f"  Reported:   ${reported:,.2f}")
    print(f"  Difference: ${calculated - reported:,.2f}")
    print()

2023-24 Allocation
  Calculated: $1,513,171.18
  Reported:   $1,513,171.18
  Difference: $0.00

2024-25 Request
  Calculated: $1,502,598.56
  Reported:   $1,502,598.56
  Difference: $0.00

2024-25 Allocation
  Calculated: $1,733,008.51
  Reported:   $1,733,008.51
  Difference: $0.00

In [16]:
df_2024_25_export = df_2024_25_raw.copy()

df_2024_25_export.insert(
    0,
    "source_document",
    "2024-25_sa_fee_memo.pdf"
)

df_2024_25_export.insert(
    1,
    "source_page",
    3
)

df_2024_25_export.insert(
    2,
    "source_url",
    "https://studentleadership.seattlecentral.edu/sites/"
    "studentleadership.seattlecentral.edu/files/"
    "2025-01/2024-25%20Student%20Services%20and%20Activities%20Fees%20Memo.pdf"
)

output_path_2024_25 = raw_dir / "2024_25_sa_budget_raw.csv"

df_2024_25_export.to_csv(
    output_path_2024_25,
    index=False
)

print("Saved to:")
print(output_path_2024_25)

Saved to:
C:\GitHub Projects\seattle-central-sa-budget-dashboard\data\raw\2024_25_sa_budget_raw.csv

In [17]:
check_2024_25 = pd.read_csv(
    output_path_2024_25,
    dtype=str,
    keep_default_na=False
)

print("Rows:", len(check_2024_25))
print("Columns:", len(check_2024_25.columns))

display(check_2024_25.tail())

Rows: 20
Columns: 7

,source_document,source_page,source_url,program_name_raw,allocation_2023_24_raw,request_2024_25_raw,allocation_2024_25_raw
15,2024-25_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Student Resource Support,"$139,203.30",$0.00,"$139,203.30"
16,2024-25_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Student Leadership Program,"$140,985.00","$169,417.55","$169,417.55"
17,2024-25_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Student Engagement,$0.00,$0.00,"$45,714.70"
18,2024-25_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Wood Technology Center,"$4,000.00","$28,860.00","$4,000.00"
19,2024-25_sa_fee_memo.pdf,3,https://studentleadership.seattlecentral.edu/s...,Total,"$1,513,171.18","$1,502,598.56","$1,733,008.51"

In [18]:
pdf_2025_26 = next(
    (
        path.resolve()
        for path in [
            cwd / "source_docs" / "2025-26_sa_budget_summary.pdf",
            cwd.parent / "source_docs" / "2025-26_sa_budget_summary.pdf",
        ]
        if path.exists()
    ),
    None
)

print("PDF found:", pdf_2025_26)

PDF found: C:\GitHub Projects\seattle-central-sa-budget-dashboard\source_docs\2025-26_sa_budget_summary.pdf

In [19]:
with pdfplumber.open(pdf_2025_26) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_number, page in enumerate(pdf.pages, start=1):
        tables = page.extract_tables()

        print(
            f"Page {page_number}: "
            f"{len(tables)} table(s) detected"
        )

        for table_number, table in enumerate(tables, start=1):
            print(f"\nTable {table_number}")

            for row in table[:10]:
                print(row)

Number of pages: 3
Page 1: 1 table(s) detected

Table 1
['', '', '', '', '']
['S&A Funded Program', '2023-24', '2024-25', '2025-26', '2025-26']
['', 'Allocation', 'Allocation', 'Request', 'Allocation']
['AANAPISI', '$0.00', '$0.00', '$44,220.15', '$36,630.28']
['ASC Book Fund', '$2,000.00', '$2,000.00', '$3,000.00', '$0.00']
['Associated Student Council', '$64,539.00', '$93,159.58', '$116,663.00', '$96,748.00']
['Child Assist Program [combined in\nSSP]', '$20,000.00', '$20,000.00', '$0.00', '--']
['Cultural Programming & Development\n(CAB)', '$116,767.00', '$128,841.99', '$149,238.00', '$148,650.92']
['Emergency Fund', '$25,000.00', '$25,000.00', '$50,000.00', '$50,000']
['First Year Experience Peer Mentors', '$0.00', '$0.00', '$57,000.00', '$20,314.25']
Page 2: 1 table(s) detected

Table 1
['M. Rosetta Hunter Art Gallery', '$57,513.00', '$58,513.79', '$94,729.09', '$77,930.27']
['Office Management', '$74,824.00', '$85,967.23', '$78,093.62', '$89,492.00']
['Phi Theta Kappa', '$35,000.00', '$36,047.71', '$58,035.85', '$42,435.85']
['Services & Activities Fees Committee', '$7,500.00', '$24,131.32', '$7,600.00', '$7,867.10']
['Student Leadership Program', '$140,985.00', '$169,417.55', '$220,539.00', '$186,665.23']
['Student Engagement', '$0.00', '$45,714.70', '$0.00', '$0.00']
['Student Organization Hub', '$120,002.63', '$127,811.35', '$136,123.00', '$134,474.20']
['Student Resource Support [combined\nin SSP]', '$139,203.30', '$139,203.30', '$0.00', '--']
['Student Support Program Supervisor', '$0.00', '$0.00', '$92,119.04', '$96,277.04']
['The Seattle Collegian', '$52,073.00', '$79,142.00', '$111,880.40', '$83,577.00']
Page 3: 0 table(s) detected

In [20]:
rows_2025_26 = []

with pdfplumber.open(pdf_2025_26) as pdf:

    # PAGE 1
    table_page_1 = pdf.pages[0].extract_tables()[0]

    # Skip:
    # row 0 = blank
    # row 1 = fiscal-year header
    # row 2 = Allocation / Request header
    for row in table_page_1[3:]:
        rows_2025_26.append(
            [1] + row
        )

    # PAGE 2
    table_page_2 = pdf.pages[1].extract_tables()[0]

    # Page 2 is a continuation, so there is no header to skip
    for row in table_page_2:
        rows_2025_26.append(
            [2] + row
        )


df_2025_26_raw = pd.DataFrame(
    rows_2025_26,
    columns=[
        "source_page",
        "program_name_raw",
        "allocation_2023_24_raw",
        "allocation_2024_25_raw",
        "request_2025_26_raw",
        "allocation_2025_26_raw",
    ],
)

display(df_2025_26_raw)

print("\nRows extracted:", len(df_2025_26_raw))

,source_page,program_name_raw,allocation_2023_24_raw,allocation_2024_25_raw,request_2025_26_raw,allocation_2025_26_raw
0,1,AANAPISI,$0.00,$0.00,"$44,220.15","$36,630.28"
1,1,ASC Book Fund,"$2,000.00","$2,000.00","$3,000.00",$0.00
2,1,Associated Student Council,"$64,539.00","$93,159.58","$116,663.00","$96,748.00"
3,1,Child Assist Program [combined in\nSSP],"$20,000.00","$20,000.00",$0.00,--
4,1,Cultural Programming & Development\n(CAB),"$116,767.00","$128,841.99","$149,238.00","$148,650.92"
5,1,Emergency Fund,"$25,000.00","$25,000.00","$50,000.00","$50,000"
6,1,First Year Experience Peer Mentors,$0.00,$0.00,"$57,000.00","$20,314.25"
7,1,"Accessibility, Community, &\nOpportunity","$9,000.00","$9,076.80","$11,700.00","$10,700.00"
8,1,Food and Resource Pantry,$0.00,$0.00,"$15,000.00","$30,000"
9,1,Information Central,"$157,950.00","$195,205.32","$238,402.00","$186,282.00"
10,1,Leadership & Orientation Training,"$16,384.00","$16,384.00","$20,000.00","$14,581.76"
11,1,Learning Support Network,"$470,430.25","$473,391.87","$503,767.04","$477,762.58"
12,2,M. Rosetta Hunter Art Gallery,"$57,513.00","$58,513.79","$94,729.09","$77,930.27"
13,2,Office Management,"$74,824.00","$85,967.23","$78,093.62","$89,492.00"
14,2,Phi Theta Kappa,"$35,000.00","$36,047.71","$58,035.85","$42,435.85"
15,2,Services & Activities Fees Committee,"$7,500.00","$24,131.32","$7,600.00","$7,867.10"
16,2,Student Leadership Program,"$140,985.00","$169,417.55","$220,539.00","$186,665.23"
17,2,Student Engagement,$0.00,"$45,714.70",$0.00,$0.00
18,2,Student Organization Hub,"$120,002.63","$127,811.35","$136,123.00","$134,474.20"
19,2,Student Resource Support [combined\nin SSP],"$139,203.30","$139,203.30",$0.00,--
20,2,Student Support Program Supervisor,$0.00,$0.00,"$92,119.04","$96,277.04"
21,2,The Seattle Collegian,"$52,073.00","$79,142.00","$111,880.40","$83,577.00"
22,2,Umoja Scholars Program,$0.00,$0.00,"$29,500.00","$7,500.00"
23,2,Wood Technology Center,"$4,000.00","$4,000.00","$9,300.00","$4,000.00"
24,2,,,,,
25,2,Total,"$1,513,171.18","$1,733,008.51","$2,046,910.19","$1,801,888.48"
26,2,,,,,

Rows extracted: 27

In [21]:
print("First 5 rows:")
display(df_2025_26_raw.head())

print("Last 10 rows:")
display(df_2025_26_raw.tail(10))

First 5 rows:

,source_page,program_name_raw,allocation_2023_24_raw,allocation_2024_25_raw,request_2025_26_raw,allocation_2025_26_raw
0,1,AANAPISI,$0.00,$0.00,"$44,220.15","$36,630.28"
1,1,ASC Book Fund,"$2,000.00","$2,000.00","$3,000.00",$0.00
2,1,Associated Student Council,"$64,539.00","$93,159.58","$116,663.00","$96,748.00"
3,1,Child Assist Program [combined in\nSSP],"$20,000.00","$20,000.00",$0.00,--
4,1,Cultural Programming & Development\n(CAB),"$116,767.00","$128,841.99","$149,238.00","$148,650.92"

Last 10 rows:

,source_page,program_name_raw,allocation_2023_24_raw,allocation_2024_25_raw,request_2025_26_raw,allocation_2025_26_raw
17,2,Student Engagement,$0.00,"$45,714.70",$0.00,$0.00
18,2,Student Organization Hub,"$120,002.63","$127,811.35","$136,123.00","$134,474.20"
19,2,Student Resource Support [combined\nin SSP],"$139,203.30","$139,203.30",$0.00,--
20,2,Student Support Program Supervisor,$0.00,$0.00,"$92,119.04","$96,277.04"
21,2,The Seattle Collegian,"$52,073.00","$79,142.00","$111,880.40","$83,577.00"
22,2,Umoja Scholars Program,$0.00,$0.00,"$29,500.00","$7,500.00"
23,2,Wood Technology Center,"$4,000.00","$4,000.00","$9,300.00","$4,000.00"
24,2,,,,,
25,2,Total,"$1,513,171.18","$1,733,008.51","$2,046,910.19","$1,801,888.48"
26,2,,,,,

In [22]:
df_2025_26_raw[
    df_2025_26_raw["program_name_raw"]
    .astype(str)
    .str.contains("total", case=False, na=False)
]

,source_page,program_name_raw,allocation_2023_24_raw,allocation_2024_25_raw,request_2025_26_raw,allocation_2025_26_raw
25,2,Total,"$1,513,171.18","$1,733,008.51","$2,046,910.19","$1,801,888.48"

In [23]:
def parse_currency_for_check(value):
    if value is None:
        return 0.0

    value = str(value).strip()

    if value in {
        "",
        "-",
        "--",
        "—",
        "–",
    }:
        return 0.0

    value = (
        value
        .replace("$", "")
        .replace(",", "")
    )

    return float(value)

In [24]:
nonblank_name = (
    df_2025_26_raw["program_name_raw"].notna()
    & df_2025_26_raw["program_name_raw"]
        .astype(str)
        .str.strip()
        .ne("")
)

df_2025_26_raw = (
    df_2025_26_raw[nonblank_name]
    .copy()
)

print("Nonblank rows:", len(df_2025_26_raw))

Nonblank rows: 25

In [25]:
total_mask_2025_26 = (
    df_2025_26_raw["program_name_raw"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("total")
)

reported_total_2025_26 = (
    df_2025_26_raw[total_mask_2025_26]
    .copy()
)

df_2025_26_programs = (
    df_2025_26_raw[~total_mask_2025_26]
    .copy()
)

print("Program rows:", len(df_2025_26_programs))

display(reported_total_2025_26)

Program rows: 24

,source_page,program_name_raw,allocation_2023_24_raw,allocation_2024_25_raw,request_2025_26_raw,allocation_2025_26_raw
25,2,Total,"$1,513,171.18","$1,733,008.51","$2,046,910.19","$1,801,888.48"

In [26]:
calculated_totals_2025_26 = {
    "2023-24 Allocation": df_2025_26_programs[
        "allocation_2023_24_raw"
    ].apply(parse_currency_for_check).sum(),

    "2024-25 Allocation": df_2025_26_programs[
        "allocation_2024_25_raw"
    ].apply(parse_currency_for_check).sum(),

    "2025-26 Request": df_2025_26_programs[
        "request_2025_26_raw"
    ].apply(parse_currency_for_check).sum(),

    "2025-26 Allocation": df_2025_26_programs[
        "allocation_2025_26_raw"
    ].apply(parse_currency_for_check).sum(),
}


reported_totals_2025_26 = {
    "2023-24 Allocation": parse_currency_for_check(
        reported_total_2025_26.iloc[0][
            "allocation_2023_24_raw"
        ]
    ),

    "2024-25 Allocation": parse_currency_for_check(
        reported_total_2025_26.iloc[0][
            "allocation_2024_25_raw"
        ]
    ),

    "2025-26 Request": parse_currency_for_check(
        reported_total_2025_26.iloc[0][
            "request_2025_26_raw"
        ]
    ),

    "2025-26 Allocation": parse_currency_for_check(
        reported_total_2025_26.iloc[0][
            "allocation_2025_26_raw"
        ]
    ),
}


for label in calculated_totals_2025_26:
    calculated = calculated_totals_2025_26[label]
    reported = reported_totals_2025_26[label]

    print(label)
    print(f"  Calculated: ${calculated:,.2f}")
    print(f"  Reported:   ${reported:,.2f}")
    print(
        f"  Difference: "
        f"${calculated - reported:,.2f}"
    )
    print()

2023-24 Allocation
  Calculated: $1,513,171.18
  Reported:   $1,513,171.18
  Difference: $0.00

2024-25 Allocation
  Calculated: $1,733,008.51
  Reported:   $1,733,008.51
  Difference: $-0.00

2025-26 Request
  Calculated: $2,046,910.19
  Reported:   $2,046,910.19
  Difference: $0.00

2025-26 Allocation
  Calculated: $1,801,888.48
  Reported:   $1,801,888.48
  Difference: $0.00

In [27]:
df_2025_26_export = df_2025_26_raw.copy()

df_2025_26_export.insert(
    0,
    "source_document",
    "2025-26_sa_budget_summary.pdf"
)

df_2025_26_export.insert(
    2,
    "source_url",
    "https://studentleadership.seattlecentral.edu/sites/"
    "studentleadership.seattlecentral.edu/files/"
    "2026-02/FY26_S%26A_Budget%20Summary_Final.pdf"
)

output_path_2025_26 = raw_dir / "2025_26_sa_budget_raw.csv"

df_2025_26_export.to_csv(
    output_path_2025_26,
    index=False
)

print("Saved to:")
print(output_path_2025_26)

Saved to:
C:\GitHub Projects\seattle-central-sa-budget-dashboard\data\raw\2025_26_sa_budget_raw.csv

In [28]:
check_2025_26 = pd.read_csv(
    output_path_2025_26,
    dtype=str,
    keep_default_na=False
)

print("Rows:", len(check_2025_26))
print("Columns:", len(check_2025_26.columns))

display(check_2025_26.head(3))
display(check_2025_26.tail(3))

Rows: 25
Columns: 8

,source_document,source_page,source_url,program_name_raw,allocation_2023_24_raw,allocation_2024_25_raw,request_2025_26_raw,allocation_2025_26_raw
0,2025-26_sa_budget_summary.pdf,1,https://studentleadership.seattlecentral.edu/s...,AANAPISI,$0.00,$0.00,"$44,220.15","$36,630.28"
1,2025-26_sa_budget_summary.pdf,1,https://studentleadership.seattlecentral.edu/s...,ASC Book Fund,"$2,000.00","$2,000.00","$3,000.00",$0.00
2,2025-26_sa_budget_summary.pdf,1,https://studentleadership.seattlecentral.edu/s...,Associated Student Council,"$64,539.00","$93,159.58","$116,663.00","$96,748.00"

,source_document,source_page,source_url,program_name_raw,allocation_2023_24_raw,allocation_2024_25_raw,request_2025_26_raw,allocation_2025_26_raw
22,2025-26_sa_budget_summary.pdf,2,https://studentleadership.seattlecentral.edu/s...,Umoja Scholars Program,$0.00,$0.00,"$29,500.00","$7,500.00"
23,2025-26_sa_budget_summary.pdf,2,https://studentleadership.seattlecentral.edu/s...,Wood Technology Center,"$4,000.00","$4,000.00","$9,300.00","$4,000.00"
24,2025-26_sa_budget_summary.pdf,2,https://studentleadership.seattlecentral.edu/s...,Total,"$1,513,171.18","$1,733,008.51","$2,046,910.19","$1,801,888.48"